### PR TITLE
issue-4: Fix problem with unwrap inside cache_ttl

### LINKED ISSUE #4: Remove `.unwrap()` from `.cache_key()` method
Implementation of Cacheable trait uses code below
```rust
let gen = quote! {
    impl Cacheable for #name {
        fn cache_key(&self) -> String {
            actix_cache::serde_qs::to_string(self).unwrap()
        }
        ...
    }
};
```

The app will panic if 'serde_qs' doesn't convert any message to a string.
We should consider the option if `serde_qs::to_string` will return Err.

### PR DESCRIPTION
**Pull request by AndreyErmilov**
Closes #4

### CODE REVIEW

File: src/cache.rs [hunk 1]
```diff
@@ -80,7 +82,7 @@ pub trait Cacheable {
     /// By default cache label is a cache key prefix: `{actor}::{message type}`.
     /// This value used for aggregating metrics by actors and message.
     fn label(&self) -> String {
-        self.cache_key()
+        self.cache_key().unwrap()
```
Comment (singulared) [inline src/cache.rs]: `label` should return Result too, i think.
Or we can remove this method. Now it's implement wrong logic.

File: src/cache.rs [hunk 2]
```diff
@@ -130,12 +132,17 @@ where
 
     fn handle(&mut self, msg: QueryCache<A, M>, _: &mut Self::Context) -> Self::Result {
         let backend = self.backend.clone();
-        let key = msg.message.cache_key();
-        let enabled = self.enabled;
+        let (enabled, cache_key) = match msg.message.cache_key() {
+            Ok(value) => (self.enabled, value),
+            Err(error) => {
+                debug!("Creating cache key error: {}", error);
```
Comment (singulared) [inline src/cache.rs]: `warn!` will be better.
